Hiding non-Konar Slayer Masters on Milestones
michael-gutman/konar-milestone-reminder pull request #1
Opened 2023-07-14 04:18 UTC by Henness0666

I added the ability to hide non-Konar Slayer Masters on task milestones. This makes the player unable to get a new task from any slayer master other than Konar (Just in case they didn't pay attention to the chat message). If hide and highlight are both selected it will outline the hidden NPC but also makes them untargetable.

2023-07-14 09:42 UTC, MrPryor commented
👍

2023-07-14 16:37 UTC, michael-gutman requested changes
Wow, awesome! Thanks for submitting this!
There are a couple of minor fixes to make. Right now this is hiding other slayer masters at all times, unless you close Runelite and open it again, in which case the hiding no longer works. 

You can check if other slayer masters should be hidden with `config.getReminderStatus()`. 
Your hide config is not working between sessions because your local `hideOtherSlayerMasters` is only updated to match `config.hideOtherSlayerMasters()` on config changes. You could try calling your `updateConfig` in more places, or just use `config.hideOtherSlayerMasters()` directly so you know its right in all situations. 

- [ ] Only hide other slayer masters when the reminder is active
- [ ] Make sure they stay hidden between sessions/log-ins

I really appreciate the contribution! This feature was requested when I first made the plugin, but I never got back around to working on it again. Thank you!

2023-07-14 16:43 UTC, Henness0666 commented
Oh, I didn't realize these issues. I guess I should have done more testing!

I will work on these changes and get back to you. :)

2023-07-15 16:48 UTC, Henness0666 commented
Should be all good now. Tested with multiple tasks, logged out, and closed the game a few times.

2023-07-19 23:24 UTC, michael-gutman approved these changes
Yup, seems to be working. Thanks!

2023-07-19 23:24 UTC, merged